# Generated by Django 3.1.7 on 2021-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='member',
            name='twitter',
            field=models.URLField(default='#'),
        ),
    ]
